-- Per-dish post-order star ratings used by menu Most Loved ranking.

create table if not exists public.dish_ratings (
  id bigint generated by default as identity primary key,
  dish_id text not null,
  dish_name text not null,
  session_id text not null,
  rating smallint not null check (rating between 1 and 5),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_dish_ratings_dish_session
  on public.dish_ratings (dish_id, session_id);

create index if not exists idx_dish_ratings_dish_id
  on public.dish_ratings (dish_id);

create index if not exists idx_dish_ratings_updated_at
  on public.dish_ratings (updated_at desc);

create index if not exists idx_dish_ratings_rating
  on public.dish_ratings (rating desc);

grant select, insert, update on table public.dish_ratings to anon, authenticated;
grant usage, select on sequence public.dish_ratings_id_seq to anon, authenticated;

alter table public.dish_ratings enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'dish_ratings' and policyname = 'dish_ratings_insert_all'
  ) then
    create policy dish_ratings_insert_all on public.dish_ratings
      for insert to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'dish_ratings' and policyname = 'dish_ratings_update_all'
  ) then
    create policy dish_ratings_update_all on public.dish_ratings
      for update to anon, authenticated
      using (true)
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'dish_ratings' and policyname = 'dish_ratings_select_all'
  ) then
    create policy dish_ratings_select_all on public.dish_ratings
      for select to anon, authenticated
      using (true);
  end if;
end $$;
