-- Analytics event tables and policies
-- Apply this migration in your Supabase project to ensure admin analytics has required data sources.

create table if not exists public.menu_views (
  id bigint generated by default as identity primary key,
  page text not null default 'menu',
  created_at timestamptz not null default now()
);

create table if not exists public.dish_views (
  id bigint generated by default as identity primary key,
  dish_id text not null,
  dish_name text not null,
  category text,
  created_at timestamptz not null default now()
);

create table if not exists public.cart_events (
  id bigint generated by default as identity primary key,
  dish_id text not null,
  dish_name text not null,
  category text,
  price numeric,
  created_at timestamptz not null default now()
);

create table if not exists public.favourites (
  id bigint generated by default as identity primary key,
  dish_id text not null,
  dish_name text not null,
  created_at timestamptz not null default now()
);

alter table public.reviews add column if not exists reviewer text;
alter table public.reviews add column if not exists text text;
alter table public.reviews add column if not exists dishes text[];
alter table public.reviews add column if not exists is_public boolean not null default false;
alter table public.reviews add column if not exists created_at timestamptz not null default now();

create index if not exists idx_menu_views_created_at on public.menu_views (created_at desc);
create index if not exists idx_dish_views_created_at on public.dish_views (created_at desc);
create index if not exists idx_dish_views_dish_name on public.dish_views (dish_name);
create index if not exists idx_cart_events_created_at on public.cart_events (created_at desc);
create index if not exists idx_cart_events_dish_name on public.cart_events (dish_name);
create index if not exists idx_favourites_created_at on public.favourites (created_at desc);
create index if not exists idx_favourites_dish_name on public.favourites (dish_name);
create index if not exists idx_reviews_created_at on public.reviews (created_at desc);

alter table public.menu_views enable row level security;
alter table public.dish_views enable row level security;
alter table public.cart_events enable row level security;
alter table public.favourites enable row level security;

-- Guests and logged-in users can write events.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'menu_views' and policyname = 'menu_views_insert_all'
  ) then
    create policy menu_views_insert_all on public.menu_views
      for insert to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'dish_views' and policyname = 'dish_views_insert_all'
  ) then
    create policy dish_views_insert_all on public.dish_views
      for insert to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'cart_events' and policyname = 'cart_events_insert_all'
  ) then
    create policy cart_events_insert_all on public.cart_events
      for insert to anon, authenticated
      with check (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'favourites' and policyname = 'favourites_insert_all'
  ) then
    create policy favourites_insert_all on public.favourites
      for insert to anon, authenticated
      with check (true);
  end if;
end $$;

-- Logged-in admins can read analytics in app; refine later to role-based policies.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'menu_views' and policyname = 'menu_views_select_authenticated'
  ) then
    create policy menu_views_select_authenticated on public.menu_views
      for select to authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'dish_views' and policyname = 'dish_views_select_authenticated'
  ) then
    create policy dish_views_select_authenticated on public.dish_views
      for select to authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'cart_events' and policyname = 'cart_events_select_authenticated'
  ) then
    create policy cart_events_select_authenticated on public.cart_events
      for select to authenticated
      using (true);
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'favourites' and policyname = 'favourites_select_authenticated'
  ) then
    create policy favourites_select_authenticated on public.favourites
      for select to authenticated
      using (true);
  end if;
end $$;
